name := "scala-gyak-06"
version := "1.0"
scalaVersion := "2.13.3"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.2.10"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.10" % "test"
libraryDependencies += "io.reactivex" %% "rxscala" % "0.27.0"